#!/bin/bash
#
# Author: Petr Zemek <s3rvac@petrzemek.net>
#
# Sends a notification to the user with the given text at the given time.
#
# Examples:
#
#     notify 14:30 my nofication
#     notify 'now + 2 minutes' my notification
#
# The second example can be shortened to
#
#     notify '+2m' my notification
#

if [ "$#" -lt 2 ]; then
	echo "usage: $(basename "$0") TIMESPEC TEXT" >&2
	exit 1
fi

TIMESPEC="$1"
shift

# Allow timespecs of the form '+Xm' or '+Xh'.
if [[ "$TIMESPEC" =~ \+([0-9]+)[mh] ]]; then
	UNIT=$([ "${TIMESPEC: -1}" = "m" ] && echo "minutes" || echo "hours")
	TIMESPEC="now + ${BASH_REMATCH[1]} $UNIT"
fi

TEXT="$*"

# The final `grep` is there to suppress the warning that is always produced by
# at ("warning: commands will be executed using /bin/sh").
#
# Use a huge expire time to prevent the message from expiring (some versions of
# notify-send seem to treat 0 as "expire the notification immediately").
echo "DISPLAY=:0.0 notify-send --icon ~/.fluxbox/icons/notification.png \
	--expire-time 100000000 '$TEXT'" | at "$TIMESPEC" 2>&1 | grep -v 'warning: commands'
