#!/bin/sh
#
# Author: Petr Zemek <s3rvac@gmail.com>
#
# Fluxbox startup script.
#

# Start fluxbox.

fluxbox &
fbpid=$!

sleep 1
{
	~/.fluxbox/scripts/setup-background.sh &
	~/.fluxbox/scripts/setup-keyboard.sh &
	~/.fluxbox/scripts/setup-mouse.sh &

	# A list of applications to be started automatically.
	wicd-client &
	volumeicon &
	yakuake &
	qstardict &
	clementine &
	parcellite &
	xfce4-power-manager &
} &

wait $fbpid
